base_url = "https://vanta.one"
compile_sass = true
build_search_index = false

ignored_content = ["*/eng4u.md"]

[extra]
seperator = "/"
nav_links = [
    { name = "home", url = "/" },
    { name = "posts", url = "/blog" },
    { name = "about", url = "/about" },
]
